# tflint-ignore: terraform_required_providers
provider "talos" {
  # The Talos provider typically doesn't require explicit configuration
  # as it works with the talosconfig file generated by the module
}
